import hashlib
import os
import sys

# Can be passed via command line or environment, so the script doesn't
# need to be touched every time the compose configuration changes:
#   python3 verify_full_column.py [mode] [n_cols] [n_steps] [n_parties]
def _arg(pos, env, default):
    if len(sys.argv) > pos:
        return sys.argv[pos]
    return os.environ.get(env, default)


mode = _arg(1, "MODE", "sequential")
n_cols = int(_arg(2, "N_COLS", 4))
n_steps = int(_arg(3, "N_STEPS", 16))
n_parties = int(_arg(4, "NUM_PARTIES", 3))

if mode not in ("sequential", "simd"):
    raise ValueError("mode debe ser 'sequential' o 'simd', recibido: %r" % mode)


def val(p, c, i):
    """Same deterministic values generated by scripts/entrypoint.sh:
    (party_id + 1) * 1000000 + c * 1000 + i (column-major order)."""
    return (p + 1) * 1000000 + c * 1000 + i


def S(c, i):
    """XOR of the values of the n_parties trustees in column c,
    position i."""
    result = 0
    for p in range(n_parties):
        result ^= val(p, c, i)
    return result


def to_bytes32(value):
    return value.to_bytes(32, byteorder="big")


def column(c):
    """Recomputes the full column c (independent of the rest). Same
    formula for both modes: MODE only changes the print order, so it
    matches the .mpc output in each case."""
    results = []

    # Base case: CRV_{c,0} = S_{c,0} (no hash)
    S_prev = S(c, 0)
    crv_prev = S_prev
    results.append(crv_prev)

    # Rest of the column: CRV_{c,i} = formula from the README
    for i in range(1, n_steps):
        # The actual value being hashed is the XOR of the previous CRV and
        # the XOR of the trustees' values at the previous position.
        T_prev = crv_prev ^ S_prev
        h = hashlib.sha256(to_bytes32(T_prev)).digest()
        H_value = int.from_bytes(h, byteorder="big")
        S_i = S(c, i)
        crv_i = H_value ^ S_i
        results.append(crv_i)
        crv_prev = crv_i
        S_prev = S_i

    return results


matrix = [column(c) for c in range(n_cols)]  # matrix[c][i] = CRV_{c,i}

if mode == "sequential":
    # Column-major order: matches the .mpc output in sequential mode.
    print(f"{n_cols} columnas de {n_steps} valores cada una (modo sequential):\n")
    for c in range(n_cols):
        print(f"--- Columna {c} ---")
        for i, r in enumerate(matrix[c]):
            print(f"CRV_{i} = 0x{r:064x}")
        print()
else:
    # Step-major order: matches the .mpc output in simd mode (for each
    # step, the n_cols columns revealed in a single open).
    print(f"Matriz completa ({n_steps} pasos x {n_cols} columnas, modo simd):\n")
    for i in range(n_steps):
        for c in range(n_cols):
            print(f"CRV_{i}_col{c} = 0x{matrix[c][i]:064x}")
